### ISSUE TITLE
rdns-forwarder instances have unencrypted root volumes

### ISSUE THREAD

**Issue by sbutler** [techservicesillinois/aws-enterprise-vpc#3]
rdns-forwarder instances are created with unencrypted root volumes. This is an issue on newer AWS accounts because Security has asked us to implement a policy that all EBS volumes are encrypted. There is no additional cost to do this.

PR #2 fixes this.

**Comment by dmrzzz** [comment]
v0.11.3 now has an optional module argument to enable encryption.

Customers with existing configurations can run `terraform init -upgrade` to pull the latest module versions on the v0.11 branch, add `encrypted = true` to the module invocations in your rdns.tf (one at a time), and then terraform apply.
